vich_uploader:
    db_driver: orm

    mappings:
        skill_image:
            uri_prefix: /images/skills
            upload_destination: '%kernel.project_dir%/public/images/skills'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer