vich_uploader:
    db_driver: orm

    mappings:
        skill_image:
            uri_prefix: /images/skills
            upload_destination: '%kernel.project_dir%/public/images/skills'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        project_image:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        experience_image:
            uri_prefix: /images/experiences
            upload_destination: '%kernel.project_dir%/public/images/experiences'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        document:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer